# Generated by Django 3.1.5 on 2021-01-12 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ratings', models.PositiveSmallIntegerField(choices=[(1, '1 - Śmieć'), (2, '2 - Straszne słaby'), (3, '3 - Słaby'), (4, '4 - Zły'), (5, '5 - OK'), (6, '6 - Oglądalny'), (7, '7 - Dobry'), (8, '8 - Bardzo dobry'), (9, '9 - Perfekcyjny'), (10, '10 - Arcydzieło')], default=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=100, unique=True)),
                ('director_photo', models.ImageField(blank=True, default='films_image/domyslny.jpg', null=True, upload_to='other/author_image_user/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('about_director', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Director',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ang_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='films_image/domyslny.jpg', null=True, upload_to='other/image_user/')),
                ('clip_movie', models.FileField(blank=True, default='videos/videoplayback.mp4', null=True, upload_to='other/videos_user/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='posts', to='movie.Category')),
                ('film_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.director')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movie',
            },
        ),
        migrations.CreateModel(
            name='TopTen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('ratings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.comment')),
            ],
            options={
                'verbose_name': 'TopTen',
                'verbose_name_plural': 'TopTen',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
    ]
