# Generated by Django 3.1.5 on 2021-02-21 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='director_photo',
            field=models.ImageField(blank=True, default='films_image/domyslny.jpg', null=True, upload_to='other/author_image/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='clip_movie',
            field=models.FileField(blank=True, default='videos/videoplayback.mp4', null=True, upload_to='other/videos_movie/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ImageField(blank=True, default='films_image/domyslny.jpg', null=True, upload_to='other/image_movie/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_photo', models.ImageField(blank=True, default='no_avatar.jpg', null=True, upload_to='other/image_user/')),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_url', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
